import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarDesktop from "@/components/Navbar/NavbarDesktop";
import NavbarMobile from "@/components/Navbar/NavbarMobile";
import Footer from "@/components/Footer";
import { isAuthenticated, getAuthUser } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isAuth = await isAuthenticated();
const authUser = await getAuthUser();

console.log("isAuth in layout:", isAuth);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header>
          <div className="w-full hidden sm:block">
            <NavbarDesktop isConnected={isAuth} user={authUser} />
          </div>
          <div className="sm:hidden fixed bottom-0 w-full">
            <NavbarMobile isConnected={isAuth} user={authUser} />
          </div>
        </header>
        <main className="w-full min-h-screen bg-white">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
