import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarDesktop from "@/components/Navbar/NavbarDesktop";
import NavbarMobile from "@/components/Navbar/NavbarMobile";
import Footer from "@/components/Footer";
import { isAuthenticated, getAuthUser } from "@/lib/auth";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isAuth = await isAuthenticated();
const authUser = await getAuthUser();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white! antialiased `}
      >
        <nav>
          <div className="w-full hidden sm:block">
            <NavbarDesktop isConnected={isAuth} user={authUser} />
          </div>
          <div className="sm:hidden fixed bottom-0 w-full z-40">
            <NavbarMobile isConnected={isAuth} user={authUser} />
          </div>
        </nav>
        <main className="w-full min-h-screen bg-white">{children}</main>
        <div className="w-full hidden sm:block">
        <Footer />
        </div>
      </body>
    </html>
  );
}
